### ISSUE TITLE
Telegram GIFs cause internal error

### ISSUE THREAD

**Issue by gsomix** [codingteam/emulsion#112]
[REDACTED] reported that GIFs from Telegram room don't appear in XMPP logs. It allows [REDACTED] to use the current situation for [DATA EXPUNGED] and ██████ evil ████, and XMPP users will not suspect anything! We need to investigate it ASAP!

Results of a preliminary inquiry shows that sending any GIFs from Telegram to XMPP causes internal error, e.g.:

```
Internal error: expected:'String Begin Token', actual:'342606', at offset:707
```

However this is not affect normal program operation.

**Comment by ForNeVeR** [comment]
[MESSAGE REDACTED]
