### ISSUE TITLE
Overquote limits shouldn't apply to Telegram's forwards

### ISSUE THREAD

**Issue by Minoru** [codingteam/emulsion#120]
AlexFails forwarded a good explanation of various `const*` thingies in C++, but [that explanation was cut short by overquoting protection](https://codingteam.org.ru/_logs/codingteam%40conference.jabber.ru/2020/10/16.html#13:32:16.586438):

> <тг> <@AlexFails> >> <@AlexFails> const - квалификатор только для чтения, в некоторых контекстах может быть посчитан на этапе компиляции
> \>\> constexpr - спецификатор для функций, переменных, который помечает, что функция будет выполняться на этапе компиляции, но если данные будут не известны в компил-тайме, то оно в рантайме выполнится
> \>\> […]

I think Emulsion should not impose those limits on forwards. If something is forwarded, it should be treated as a message, and be bridged in all its fullness.

**Comment by gsomix** [comment]
I'm on it.
