### ISSUE TITLE
Forwards from Telegram hidden users and channels are considered as users' own messages in XMPP

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/emulsion#124]
Telegram has a feature for user to disallow showing their identity when forwarding their messages.

For example, `@foxtran` has this feature enabled. When his messages are forwarded by another user, they're shown as posted by that user in XMPP, and not considered as forwarded messages.

The same goes for channels: messages forwarded from Telegram channels don't show their origin or the fact they're forwarded.

**Comment by gsomix** [comment]
I'm on it.

**Comment by FulgurIgor** [comment]
It was not fully fixed: I (@foxtran) have tried to forward a message from a channel, and, in XMPP, I saw that the forwarded message is from me but not from the channel.

**Comment by ForNeVeR** [comment]
I, ~~Cato Sicarius~~ Friedrich von Never, still haven't released a package with this update.
