### ISSUE TITLE
Incident: the bot left the XMPP room at 2021-09-21T21:04:20Z

### ISSUE THREAD

**Issue by Minoru** [codingteam/emulsion#142]
The bot [left the room](https://codingteam.org.ru/_logs/codingteam%40conference.jabber.ru/2021/09/22.html#00:04:19.841186) and never returned.

**Comment by ForNeVeR** [comment]
Ok, this time, the bot sent the authentication stanza to the server (``<auth mechanism=\"SCRAM-SHA-1\" xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\">[…]`), but never received an answer. The server should've sent us the `<challenge>`, but it didn't.

This is more or less the same problem as #141, I am working on a fix.
