### ISSUE TITLE
Possibly incorrect content type specification for animations.

### ISSUE THREAD

**Issue by ttldtor** [codingteam/emulsion#169]
Found a problem with browsers Opera (91.0.4516.20, Windows 10 64-bit), Chrome (106.0.5249.103, 64 bit). They incorrectly display animations from Telegram. Show a gray square. 
![изображение](https://user-images.githubusercontent.com/3264871/194299236-d78be3f1-8a7a-41f8-804e-8b92088411e0.png)

The content type returned by the server is **image/jpeg**.
That being said, Firefox successfully plays it as **webm**.
Here is an example:

https://fornever.me/emulsion/ct/content/bKSLSDN

**Comment by ForNeVeR** [comment]
It is likely that we are incorrectly assuming `image/jpeg` content type for stickers: https://github.com/codingteam/emulsion/blob/739786463de8c34ee3a256285c74aa80eb86c2d8/Emulsion.Telegram/LinkGenerator.fs#L82
