### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/emulsion#6]
The bot should support a configuration file (probably the standard App.config would be enough, but I don't know if it's still the "standard" way of doing things on .NET Core).

XMPP and Telegram parameters should be read from the configuration file; its format should be documented.

**Comment by Newlifer** [comment]
Which format we will use? JSON or YAML or just INI?

**Comment by ForNeVeR** [comment]
I suggest to use JSON file in the current application directory.

I've found that .NET Core have no standard `ConfigurationManager` support, but there's a convenient package in NuGet. Please [read the following manual](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration).

_(You'll have to port the code to F#, but it should be straightforward enough; feel free to ask me additional questions if you stuck.)_
