### ISSUE TITLE
Separate Start action on the message system

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/emulsion#66]
To properly implement #18, we need multistage initialization for the message system.

Message system should support being in a state when it was already started (asynchronously), but it isn't ready to accept any messages yet.

I also propose we support the message system _states_, such as _disconnected_, _connecting_, _ready_. The message sender subsystem should be aware of these states and should not be trying to send the messages if the message system isn't ready.

To enhance the sender, we'll need to improve the way it is working with messages. Currently, it works as follows:

1. Gets the message from the message box
2. Tries to send the message
3. If it fails, then wait for a while and go back to step 2

If we're going to check the message system state before sending a message, then there're 2 approaches possible:

1. We may store the information in the sender actor. If we do it, then it will receive the status updates from the message system, and should process these updates with priority. Thus we'll need to rework the way it processes all the messages: it will need to maintain internal message queue (instead of using the message box as the message queue), check for the status and any incoming messages each time, and then look at the status and if it should send the messages in the current status.
2. It could just check the status of the message queue each time before sending a message. Since both approaches aren't race-free and this one looks simpler, we may start from it.

**Comment by Minoru** [comment]
If the message system is an actor as well, it can return a "receipt" with its current status. Sender will send the first message, and keep sending them as long as receipt says "success". On error, the sender will sleep for a while and retry. This way there are no races.

-- 
Regards,
Alexander Batischev

**Comment by ForNeVeR** [comment]
> If the message system is an actor as well

No, currently the message system isn't an actor, and I don't want to make it an actor (e.g. an actor in Akka terms) because of how it behaves in regards to restarts.

> Sender will send the first message, and keep sending them as long as receipt says "success".

Well, it is something we already do. The only visible change I propose here is: let's not send the messages until the message system is ready to accept them. I believe that the sender should properly coordinate with the system asynchronous start (where _the start_ actually includes many things: connection to the server, authentication, entering the rooms and things as such), and should never send the messages until it knows that the system is ready to accept them (or at least it _thinks_ it is ready).

> there are no races.

There're always races in our system, unfortunately, because other parties may close our connections in the middle of us sending a network message. But it is the only **unavoidable** race condition I am talking about, every other case should be covered.

For example, we won't simultaneously send multiple messages through one socket, because our system is designed to never do that (no races on our side).
